### ISSUE TITLE
Persona 4 Golden gradually getting slower

### ISSUE THREAD

**Issue by Jambang0812** [Vita3K/Vita3K-Android#404]
Android device specs
CPU : MediaTek Helio G85 ( Mali GPU )
RAM : 4 GB

Persona 4 Golden on my device is gradually getting slower on the frames, and is very slow at school. Can you tell me what settings I should use or can the devs please lower the extreme RAM usage, or fix it in any way.

**Comment by Jambang0812** [comment]
vita3k v7

**Comment by Jambang0812** [comment]
vita3k v7

**Comment by ashifolfi** [comment]
I would like to second this issue. I am experiencing similar/same issues on my Qualcomm Samsung Galaxy S10e.

Upon a fresh session the game is buttery smooth in most/all areas I've been in so far (pre persona awakening) but as I move around and spend more time the game begins to slow further and further jntil becoming unplayable.

I noticed that more significant speed drops seemingly occurred when changing between areas which might provide some insight into what might be happening.

My device specs:
Qualcomm Snapdragon 855
Adreno 640 GPU
~6GB RAM

**Comment by Lunakrypt** [comment]
I would like to third this issue.  Game runs perfectly smooth for a bit, then over time slows down to a crawl.  I don't play any heavy action games, mainly tactical games.

Motorola Moto G Stylus 2022
Qualcomm Snapdragon 695
Adreno 619
6 GB Ram

**Comment by Ze3e3** [comment]
I would like to fourth this issue. Game runs smooth for a certain amount of time then after a while fps dips and becomes unplayable. 

Tecno Camon 20 pro 5g
Dimensity 8050
mali g77
8gbram

**Comment by kungzkiee** [comment]
Fifth on this issue, the game become slower as i progress.. i need to restart vita3k to make it playable again..

my device:

Tecno Camon 20 Pro 5g
Dimensity 8050
8gb Ram
Mali G77

**Comment by kungzkiee** [comment]
i wish there's a fix on this issue.. 😁😁

**Comment by Macdu** [comment]
Hopefully this should be fixed in the next version (v8, not yet released).

**Comment by Lunakrypt** [comment]
Alright, so far with version 8 it seems to be working better.  I have not had time to play it extensively, but it is definitely able to go for at least a half hour of continuous play without slowing down.

**Comment by paulmichael02** [comment]
I would like to ....-th this problem, works fine for the last few mins, then sudden lag. Fps drops to 20-25 I can make it run smoothly again by going back to the menu(in game menu) and opening any of the skill menu or item menu(back to 30fps, and then repeat) it lags at any place of the game, the Shopping district, the school, the dungeons, battle, and cutscenes aswell most places of the game I say. Doesn't lag in Dojima Residence's though. It does at any resolution. Also, I finished the game completely(would like to play NG+ aswell) Hope this problem reaches, thank you.

OPPO Reno8 T
Helio G99 octa-core
CPH2481
RAM 8.00GB

**Comment by lapizvayneschnee** [comment]
still happeneing.
funny thing is in my case if may battery was 100% it runs silky smooth but when i closed the emulator and try to run the game again its just getting slower gradually, especially in shop area im using vita3k build 4001

here's my specs:
Mali-G52 MP2
MediaTek Helio G85
4gb ram
samsung A05
