### ISSUE TITLE
[Android] Left stick is not working as it should.

### ISSUE THREAD

**Issue by AlphaVecto** [Vita3K/Vita3K-Android#463]
Hello there, devs! Here's my problem: I'm currently playing P4G on Android, and every now and then when I try to run in the game (even though I'm pushing the stick fully forward) I get locked to walking speed. I believe the stick thinks I'm pulling back a bit, therefore it puts me at walking speed. It's very annoying, and I'm hoping this gets fixed soon.

**Comment by tsukina22** [comment]
I'm having this problem but in the other way around, i get locked in the running speed, even the NPCs are running, i can't just walk.

**Comment by pokannce** [comment]
Yeah I'm having this issue too when playing digimon cybersleuth, the left axis controller feels janky and does not work as intended. hoping it will be fixed soon.

**Comment by 4tl4sh** [comment]
I think that this problem can be related to an issue with Gravity Rush where whenever you change direction while running the character starts walking again. This happens with Xbox Controller as well as Gamesir G8 but not with Dualsense.

**Comment by TryingToLove** [comment]
Having the exact same issue with non-Android version as well, on Steam Deck. Diagonal left stick movements suddenly leave character moving as in slow motion. Doesn’t happen on any other emulator for me.

**Comment by DevParade** [comment]
This was an issue with the PPSSPP as well. It seemed like the L-stick only reads square input, which is why the diagonals are limited (kind of like deadzones). This was fixed by having an option to force circular input for the analog stick in the emulator. I'm wondering if this is what's causing the same issue, and if this same option can be implemented in the Vita3k as a potential fix.

**Comment by 4tl4sh** [comment]
> This was an issue with the PPSSPP as well. It seemed like the L-stick only reads square input, which is why the diagonals are limited (kind of like deadzones). This was fixed by having an option to force circular input for the analog stick in the emulator. I'm wondering if this is what's causing the same issue, and if this same option can be implemented in the Vita3k as a potential fix.

It seems so. This is the message I left in a linked issue:

This issue seems to affect many games that modulate walking/running speed by analog inclination. It seems that since Version 9 you can run diagonally when using overlay controls, but if you use any controller other than Dualsense (I can't speak by my testing of previous PlayStation controllers) the full diagonals may not be reached. A controller calibration or any other solution should be implemented to mitigate this issue. This issue affects also Vita3k's main development. 

Possibly related issues:
- https://github.com/Vita3K/Vita3K-Android/issues/431
- https://github.com/Vita3K/Vita3K/issues/2892

A reference from other project:
- https://github.com/hrydgard/ppsspp/issues/11552

**Comment by AnomalousUnderdog** [comment]
This happens to me with both controllers that I have: DualShock 4, and an 8BitDo Pro 2 (the latest one with hall effect joysticks). I'm playing Trails of Cold Steel, thankfully not too much of a problem since it's a turn-based game, but it still throws me off.

**Comment by anas-aldolimi** [comment]
did anyone arrive at a fix for android?

**Comment by 9999BOi** [comment]
I had this issue with 3 games:

1. Digimon Story Cyber Sleuth
2. Digimon Story Hacker's Memory
3. Gravity Rush

Unlike the OP, I do NOT encounter this problem with Persona 4 Golden for some reason.

I tested with 3 controllers:

1. BSP-D11: All diagonal directions results in walking speed.
2. Dualshock 4: Only DOWN+LEFT and DOWN+RIGHT results in walking speed.
3. Mocute-060: No issue.

Note that, it was not always like this. All of these controllers worked just fine before. I only encountered the problem when I deleted the custom configuration for the games. So, I cannot tell if it was the controllers or the configs that caused it.

What I've tried:

1. Uninstalling Vita3K.
2. Installing other (previous) versions of Vita3K.
3. Deleting the system storage folder (emulator path) while keeping the installed games in "ux0" folder and reinstalling Vita3K.
4. Adjusting different settings in the GPU settings.

On another note, whenever I tapped "Controls>Controller" the app would crash.
